In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [19]:
df.sample(5)

     review education purchased
43     Poor        PG        No
8   Average        UG        No
17     Poor        UG       Yes
5   Average    School       Yes
12     Poor    School        No

In [20]:
df = df.iloc[:,2:]

In [10]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [30]:
X_train

   purchased
15        No
25        No
27        No
37       Yes
20       Yes
9        Yes
32       Yes
31       Yes
45       Yes
0         No
3         No
35       Yes
42       Yes
26        No
23        No
47       Yes
28        No
39        No
49        No
38        No
21        No
19       Yes
17       Yes
13        No
10       Yes
40        No
43        No
44        No
5        Yes
6         No
29       Yes
11       Yes
48       Yes
7        Yes
36       Yes
8         No
22       Yes
33       Yes
34        No
12        No

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
X_train

   purchased
15        No
25        No
27        No
37       Yes
20       Yes
9        Yes
32       Yes
31       Yes
45       Yes
0         No
3         No
35       Yes
42       Yes
26        No
23        No
47       Yes
28        No
39        No
49        No
38        No
21        No
19       Yes
17       Yes
13        No
10       Yes
40        No
43        No
44        No
5        Yes
6         No
29       Yes
11       Yes
48       Yes
7        Yes
36       Yes
8         No
22       Yes
33       Yes
34        No
12        No

In [24]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])