In [1]:
import pandas as pd
import numpy as np 
import scipy.stats as stats
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.preprocessing import FunctionTransformer
from sklearn.compose import ColumnTransformer

In [3]:
df = pd.read_csv(f'F://datasets//titanic_dataset.csv', usecols=['age', 'fare', 'survived'])

In [4]:
df.head()

   survived   age     fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [5]:
df.isnull().sum()

survived      0
age         177
fare          0
dtype: int64

In [7]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [8]:
df.head()

   survived   age     fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [9]:
X= df.iloc[:,1:3]
y= df.iloc[:,0]

In [10]:
X_tain, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)